steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/terraform-agent:$SHORT_SHA', '.' ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/docker_password/versions/latest
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_NUMBER/secrets/docker_username/versions/latest
    env: 'USERNAME'
images:
- 'gcr.io/$PROJECT_ID/terraform-agent:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/europe-west3/workerPools/test-private-pool'
